FROM hellodk/spark-py:v1

COPY aws-java-sdk-1.7.4.jar $SPARK_HOME/jars/
COPY hadoop-aws-2.7.3.jar $SPARK_HOME/jars/
COPY jets3t-0.9.4.jar $SPARK_HOME/jars/
COPY java-xmlbuilder-1.3.jar $SPARK_HOME/jars/
